language: python
sudo: false

cache:
  apt: true
  directories:
  - $HOME/.cache/pip
  - $HOME/download
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - pip install pip -U
  - pip install -r requirements.txt -U
install:
  - travis_retry pip install -e .
script: 
  - travis_wait pytest --xdoctest --cov-config=.coveragerc --cov-report=html --cov=timerit
after_success: 
  #- coveralls || echo "Coveralls upload failed"
  - codecov 
#after_failure: 
#  - cat failed_doctests.txt
cache: 
    apt: true
    directories:
        - $HOME/.pip-cache
