#!/usr/bin/env bash
# Regenerate uv.lock and the pinned lock files in requirements/locks/.
#
# Run this whenever a dependency in pyproject.toml changes so the
# strict CI variants install the same versions you tested locally.
#
# This script is generated by xcookie; see
# xcookie/main.py:build_refresh_locks_sh.  Manual edits will be
# overwritten on the next regeneration.
set -euo pipefail

cd "$(dirname "$0")/.."

mkdir -p requirements/locks
uv lock

# Strict CI variant extras: tests
uv export --frozen --no-emit-project --format requirements.txt --no-hashes \
    --extra tests \
    -o requirements/locks/tests.txt

# Strict CI variant extras: tests, optional
uv export --frozen --no-emit-project --format requirements.txt --no-hashes \
    --extra tests \
    --extra optional \
    -o requirements/locks/tests-optional.txt
