export VARNAME_CI_SECRET="PYUTILS_CI_SECRET"
export GPG_IDENTIFIER="=PyUtils-CI <openpyutils@gmail.com>"
export VARNAME_TWINE_PASSWORD="PYUTILS_TWINE_PASSWORD"
export VARNAME_TWINE_PASSWORD="PYUTILS_TWINE_PASSWORD"
