# Python CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
# References:
#     # how to setup multiple python versions
#     https://stackoverflow.com/questions/948354/default-behavior-of-git-push-without-a-branch-specified
#     https://github.com/adambrenecki/virtualfish/blob/aa3d6271bcb86ad27b6d24f96b5bd386d176f588/.circleci/config.yml
#
#     # Multiple files for a checksum
#     https://discuss.circleci.com/t/cant-checksum-multiple-files-with-slashes-in-the-file-path/20667/2
version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-minimal-3.6
      - test-minimal-3.5
      - test-minimal-2.7

jobs:

  # DEFINE minimal dependency install and tests
  # define the "test-minimal-3.6" job and register it as a template
  test-minimal-3.6: &test-minimal-template  
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo-test-minimal-3.6
    steps:
      - checkout
      # <FAST DEPENDENCIES>
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements/runtime.txt" }}-{{ checksum "requirements/tests.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python -m venv venv || virtualenv venv  # first command is python3 || second is python2
            . venv/bin/activate
            # The minimal test requirements
            cat requirements/tests.txt > /tmp/_cci_minimal_deps_progiter.txt
            cat requirements/runtime.txt >> /tmp/_cci_minimal_deps_progiter.txt
            pip install -r /tmp/_cci_minimal_deps_progiter.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements/runtime.txt" }}-{{ checksum "requirements/tests.txt" }}
      # </FAST DEPENDENCIES>
      
      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python run_tests.py

      - store_artifacts:
          path: test-reports
          destination: test-reports


  # Define tests fo the other python verisons using the "test3.6" template
  # and indicating what needs to be modified.
  test-minimal-3.5:
    <<: *test-minimal-template
    docker:
      # All we need to do is change the base docker image so python is the
      # version we want we can reuse everything else from the template
      - image: circleci/python:3.5
    working_directory: ~/repo-test-minimal-3.5


  # < WARNING: SOON TO BE DEPRICATED >
  test-minimal-2.7:
    <<: *test-minimal-template
    docker:
      - image: circleci/python:2.7
    working_directory: ~/repo-test-minimal-2.7
  # < /WARNING: SOON TO BE DEPRICATED >
